@startuml
class Pedido {
  -idPedido: String
  -fecha: Date
  +calcularTotal(): double
}

class Producto {
  -idProducto: int
  -nombre: String
  -precio: double
}

' Asociación N-M (Muchos a Muchos)
Pedido -- Producto
@enduml